name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Install Google Chrome
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      id: setup-chrome
    - run: chmod +x ./scripts/InstallChrome.sh
    - if: runner.os == 'Linux' || runner.os == 'macOS'
      run: |
        "${{ steps.setup-chrome.outputs.chrome-path }}" --version
    - if: runner.os == 'Windows'
      run: |
        (Get-Item (Get-Command "${{ steps.setup-chrome.outputs.chrome-path }}").Source).VersionInfo.ProductVersion

    - name: Build with Maven
      run: mvn -B package --file pom.xml test

    # Update dependency graph using the full commit SHA
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
